#!/usr/bin/env bun
/**
 * Auto-generates scripts/README.md from scripts/SCRIPTS.md (SSOT)
 * @version 1.1.0
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { cwd } from 'node:process';

const ROOT = cwd();
const SCRIPTS_MD = join(ROOT, 'scripts', 'SCRIPTS.md');
const README_MD = join(ROOT, 'scripts', 'README.md');
const TEMPLATE_README_MD = join(ROOT, 'templates', 'common', 'scripts', 'README.md');
const TEMPLATE_README_DIR = dirname(TEMPLATE_README_MD);

try {
  if (!existsSync(SCRIPTS_MD)) {
    console.log('SCRIPTS.md not found, skipping generation.');
    process.exit(0);
  }

  const content = readFileSync(SCRIPTS_MD, 'utf-8');
  const guideIndex = content.indexOf('## Guide');
  
  if (guideIndex === -1) {
    console.error('Could not find ## Guide in SCRIPTS.md');
    process.exit(1);
  }

  // Extract from ## Guide until ## Version Bump Policy or end of file
  let endIndex = content.indexOf('## Version Bump Policy', guideIndex);
  if (endIndex === -1) endIndex = content.length;

  const guideContent = content.substring(guideIndex, endIndex).trim();
  
  const staticFooter = `
---

## Usage Examples

### Create a New Project
\`\`\`bash
bash scripts/new-project.sh "my-project"
cd my-project
\`\`\`

### Run Development Sync
\`\`\`bash
bash scripts/dev-sync.sh "feat: description"
# or
.\\scripts\\dev-sync.ps1 "feat: description"
\`\`\`

### Run Agent Scripts (from project directory)
\`\`\`bash
# List agents
bun run agent:list

# Create a new agent
bun run agent:create security-auditor --group Technical

# Dispatch parallel tasks
bun run dispatch:parallel
\`\`\`

### Run Lifecycle Audits
\`\`\`bash
# Check agent health
bun scripts/agent-lifecycle-audit.ts

# Check skill health
bun scripts/skill-lifecycle-audit.ts
\`\`\`

---

## File Encoding

All scripts MUST be saved as **UTF-8 (without BOM)**.

PowerShell scripts must explicitly specify encoding for outputs:
\`\`\`powershell
Add-Content -Path "file.txt" -Value "content" -Encoding UTF8
\`\`\`

---
*Last Updated: ${new Date().toISOString().split('T')[0]}*
`;

  const readmeContent = `# Workspace Scripts

> **⚠️ AUTO-GENERATED FILE**: This file is automatically generated from \`scripts/SCRIPTS.md\`.
> Do not edit this file directly. Modify \`SCRIPTS.md\` instead.

${guideContent.replace('## Guide', '## Script Categories')}

${staticFooter}`;

  // Write to workspace root
  writeFileSync(README_MD, readmeContent, 'utf-8');

  // Write to template — only if this repo actually has a templates/common/scripts/
  // tree to keep in sync (this project is a standalone L2 deployment and does not).
  if (existsSync(TEMPLATE_README_DIR)) {
    if (existsSync(TEMPLATE_README_MD)) {
      require('node:fs').chmodSync(TEMPLATE_README_MD, 0o644);
    }
    writeFileSync(TEMPLATE_README_MD, readmeContent, 'utf-8');
    require('node:fs').chmodSync(TEMPLATE_README_MD, 0o444);
  }

  console.log('✅ Generated scripts/README.md from SCRIPTS.md');
} catch (e) {
  console.error('Failed to generate README.md:', e);
  process.exit(1);
}
