#!/usr/bin/env bun
/**
 * Skill Verification Script
 * @version 1.0.0
 * Verifies all skills in skills/ directory are loadable and properly formatted
 */

import path from "node:path";

const scriptDir = path.dirname(import.meta.path);
const projectRoot = path.resolve(scriptDir, "..");

interface SkillCheck {
  name: string;
  path: string;
  status: "PASS" | "FAIL" | "WARN";
  issues: string[];
}

/**
 * Skill metadata for auto-discovery
 * Extracted from frontmatter and content
 */
interface SkillMetadata {
  name: string;
  description: string;
  type: string;
  triggers: string[];
}

async function main(): Promise<void> {
  console.log("🔍 Verifying Skills\n");

  const checks = await scanSkills();

  for (const check of checks) {
    const icon = check.status === "PASS" ? "✅" : check.status === "WARN" ? "⚠️" : "❌";
    console.log(`${icon} ${check.name}`);
    for (const issue of check.issues) {
      console.log(`   ${issue}`);
    }
  }

  const failed = checks.filter(c => c.status === "FAIL").length;
  const warned = checks.filter(c => c.status === "WARN").length;

  console.log(`\n${checks.length} skills checked`);
  if (failed > 0) {
    console.log(`❌ ${failed} failed`);
    process.exit(1);
  } else if (warned > 0) {
    console.log(`⚠️  ${warned} warnings`);
  } else {
    console.log("✅ All skills verified");
  }

  // Generate skills index
  await generateSkillsIndex(checks);
}

async function scanSkills(): Promise<SkillCheck[]> {
  const checks: SkillCheck[] = [];

  // Use native filesystem API for cross-platform compatibility
  async function scanDirectory(dir: string): Promise<string[]> {
    const files: string[] = [];
    const skillsPath = path.isAbsolute(dir) ? dir : path.join(projectRoot, dir);

    for await (const entry of Bun.glob(`${skillsPath}/**/*`)) {
      if (entry.endsWith("SKILL.md")) {
        files.push(entry);
      }
    }
    return files;
  }

  const skillFiles = await scanDirectory("skills");

  for (const skillFile of skillFiles) {
    const check = await verifySkill(skillFile);
    checks.push(check);
  }

  return checks;
}

/**
 * Extract skill metadata for auto-discovery
 * Parses frontmatter and content to generate skill catalog
 */
function extractSkillMetadata(content: string, skillPath: string): SkillMetadata {
  const metadata: SkillMetadata = {
    name: "",
    description: "",
    type: "unknown",
    triggers: []
  };

  // Extract frontmatter
  const frontmatterStart = content.indexOf("---");
  const frontmatterEnd = content.indexOf("---", 3);

  if (frontmatterStart !== -1 && frontmatterEnd !== -1) {
    const frontmatter = content.substring(frontmatterStart + 3, frontmatterEnd);

    const nameMatch = frontmatter.match(/name:\s*(.+)/);
    if (nameMatch) metadata.name = nameMatch[1].trim();

    const descMatch = frontmatter.match(/description:\s*(.+)/);
    if (descMatch) metadata.description = descMatch[1].trim();

    const typeMatch = frontmatter.match(/metadata:\s*\n\s*type:\s*(.+)/);
    if (typeMatch) metadata.type = typeMatch[1].trim();
  }

  // Extract triggers from content
  const triggerMatch = content.match(/(?:## Trigger|When to Use):\s*\n([^#]+)/);
  if (triggerMatch) {
    const triggers = triggerMatch[1].split('\n')
      .map(line => line.trim().replace(/^[-*]\s*/, ''))
      .filter(line => line.length > 0);
    metadata.triggers = triggers;
  }

  return metadata;
}

/**
 * Generate SKILLS.md index from discovered skills
 */
async function generateSkillsIndex(checks: SkillCheck[]): Promise<void> {
  const indexPath = path.join(projectRoot, "skills", "SKILLS.md");
  let content = "# Skills Index\n\n";
  content += "> Auto-generated by verify-skills.ts. Do not edit manually.\n\n";
  content += `Generated: ${new Date().toISOString()}\n\n`;

  const skillsByType = new Map<string, SkillCheck[]>();

  for (const check of checks) {
    try {
      const fileContent = await Bun.file(check.path).text();
      const metadata = extractSkillMetadata(fileContent, check.path);
      const type = metadata.type || "uncategorized";

      if (!skillsByType.has(type)) {
        skillsByType.set(type, []);
      }
      skillsByType.get(type)!.push(check);
    } catch {
      // Skip files that can't be read
    }
  }

  for (const [type, typeChecks] of skillsByType) {
    content += `## ${type.charAt(0).toUpperCase() + type.slice(1)}\n\n`;
    for (const check of typeChecks) {
      content += `- [${check.name}](skills/${check.name}/SKILL.md)\n`;
    }
    content += "\n";
  }

  await Bun.write(indexPath, content);
  console.log(`\n📝 Generated skills index: ${indexPath}`);
}

async function verifySkill(skillFile: string): Promise<SkillCheck> {
  const issues: string[] = [];
  let status: "PASS" | "FAIL" | "WARN" = "PASS";

  try {
    const content = await Bun.file(skillFile).text();

    // Check for frontmatter
    if (!content.startsWith("---")) {
      issues.push("Missing frontmatter");
      status = "FAIL";
    } else {
      // Extract frontmatter
      const frontmatterEnd = content.indexOf("---", 3);
      if (frontmatterEnd === -1) {
        issues.push("Invalid frontmatter (missing closing ---)");
        status = "FAIL";
      } else {
        const frontmatter = content.substring(3, frontmatterEnd);

        // Check required fields
        if (!frontmatter.includes("name:")) {
          issues.push("Missing 'name' field");
          status = "FAIL";
        }
        if (!frontmatter.includes("description:")) {
          issues.push("Missing 'description' field");
          status = "WARN";
        }
        if (!frontmatter.includes("metadata:")) {
          issues.push("Missing 'metadata' section");
          status = "WARN";
        }
      }
    }

    // Check for content after frontmatter
    const contentStart = content.indexOf("---", 3);
    if (contentStart !== -1) {
      const bodyContent = content.substring(contentStart + 3).trim();
      if (bodyContent.length < 50) {
        issues.push("Skill content seems too short");
        status = "WARN";
      }
    }

    const skillName = skillFile.match(/skills\/([^/]+)\//)?.[1] || skillFile;

    return {
      name: skillName,
      path: skillFile,
      status,
      issues
    };
  } catch (error) {
    return {
      name: skillFile,
      path: skillFile,
      status: "FAIL",
      issues: [`Failed to read: ${error}`]
    };
  }
}

main();
